# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import numpy as np
import pandas as pd


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_serial = QtWidgets.QLabel(self.centralwidget)
        self.label_serial.setGeometry(QtCore.QRect(20, 19, 1061, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(16)
        self.label_serial.setFont(font)
        self.label_serial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serial.setObjectName("label_serial")
        self.textBrowser_serial = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_serial.setGeometry(QtCore.QRect(20, 75, 1061, 51))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(14)
        self.textBrowser_serial.setFont(font)
        self.textBrowser_serial.setObjectName("textBrowser_serial")
        self.pushButto_granted = QtWidgets.QPushButton(self.centralwidget)
        self.pushButto_granted.setGeometry(QtCore.QRect(20, 210, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButto_granted.setFont(font)
        self.pushButto_granted.setObjectName("pushButto_granted")
        self.pushButto_denied = QtWidgets.QPushButton(self.centralwidget)
        self.pushButto_denied.setGeometry(QtCore.QRect(920, 210, 160, 51))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButto_denied.setFont(font)
        self.pushButto_denied.setObjectName("pushButto_denied")
        self.pushButto_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButto_reset.setGeometry(QtCore.QRect(480, 210, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButto_reset.setFont(font)
        self.pushButto_reset.setObjectName("pushButto_reset")
        self.textBrowser_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_output.setGeometry(QtCore.QRect(252, 143, 691, 51))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(14)
        self.textBrowser_output.setFont(font)
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(20, 150, 211, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(12)
        self.label_output.setFont(font)
        self.label_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output.setObjectName("label_output")
        self.pushButton_output = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_output.setGeometry(QtCore.QRect(958, 143, 121, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.pushButton_output.setFont(font)
        self.pushButton_output.setObjectName("pushButton_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_output.clicked.connect(self.getOutput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RFID_GUI"))
        self.label_serial.setText(_translate("MainWindow", "Serial Number"))
        self.pushButto_granted.setText(_translate("MainWindow", "Granted"))
        self.pushButto_denied.setText(_translate("MainWindow", "Denied"))
        self.pushButto_reset.setText(_translate("MainWindow", "Reset"))
        self.label_output.setText(_translate("MainWindow", "Output Folder :"))
        self.pushButton_output.setText(_translate("MainWindow", "Select"))

    def getOutput(self):
        selected_dir = QtWidgets.QFileDialog.getExistingDirectory(
            None, caption='Choose Directory', directory=os.getcwd())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
