# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
import sys


class Window3(object):
    def __init__(self, serial, name, id_no, gender, db):
        self.name = name
        self.serial = serial
        self.id = id_no
        self.gender = gender
        self.db = db

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 492)
        MainWindow.setStyleSheet("background-color: rgb(40, 39, 44);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name_edit = QtWidgets.QLabel(self.centralwidget)
        self.label_name_edit.setGeometry(QtCore.QRect(20, 162, 101, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_name_edit.setFont(font)
        self.label_name_edit.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_name_edit.setObjectName("label_name_edit")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(140, 152, 631, 51))
        font = QtGui.QFont()
        font.setFamily("SWLink")
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 781, 31))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_id_edit = QtWidgets.QLabel(self.centralwidget)
        self.label_id_edit.setGeometry(QtCore.QRect(20, 242, 211, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_id_edit.setFont(font)
        self.label_id_edit.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_id_edit.setObjectName("label_id_edit")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(240, 232, 531, 51))
        font = QtGui.QFont()
        font.setFamily("SWLink")
        font.setPointSize(12)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_gender_edit = QtWidgets.QLabel(self.centralwidget)
        self.label_gender_edit.setGeometry(QtCore.QRect(20, 322, 131, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_gender_edit.setFont(font)
        self.label_gender_edit.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_gender_edit.setObjectName("label_gender_edit")
        self.lineEdit_gender = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gender.setGeometry(QtCore.QRect(180, 312, 591, 51))
        font = QtGui.QFont()
        font.setFamily("SWLink")
        font.setPointSize(12)
        self.lineEdit_gender.setFont(font)
        self.lineEdit_gender.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_gender.setObjectName("lineEdit_gender")
        self.label_serial_edit = QtWidgets.QLabel(self.centralwidget)
        self.label_serial_edit.setGeometry(QtCore.QRect(20, 86, 191, 21))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_serial_edit.setFont(font)
        self.label_serial_edit.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_serial_edit.setObjectName("label_serial_edit")
        self.textBrowser_edit_serial = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.textBrowser_edit_serial.setGeometry(
            QtCore.QRect(210, 76, 561, 51))
        self.textBrowser_edit_serial.setStyleSheet(
            "color: rgb(255, 255, 255);")
        self.textBrowser_edit_serial.setObjectName("textBrowser_edit_serial")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(660, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Prestige Elite Std")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 127);\n"
                                      "border-radius : 10px;")
        self.pushButton.setObjectName("pushButton")
        self.label_prog = QtWidgets.QLabel(self.centralwidget)
        self.label_prog.setGeometry(QtCore.QRect(25, 400, 250, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(16)
        self.label_prog.setFont(font)
        self.label_prog.setText("")
        self.label_prog.setObjectName("label_prog")
        self.label_prog.setStyleSheet("color: rgb(255, 255, 255);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.textBrowser_edit_serial.setText(str(self.serial))
        self.lineEdit_name.setText(self.name)
        self.lineEdit_id.setText(self.id)
        self.lineEdit_gender.setText(self.gender)

        self.pushButton.clicked.connect(self.submit_detail)

    def submit_detail(self):
        self.data = pd.read_csv(self.db)
        if self.serial in self.data.Serial.unique():
            self.data.loc[self.data.Serial==self.serial, 'Name'] = self.lineEdit_name.text()
            self.data.loc[self.data.Serial==self.serial, 'Employee ID'] = self.lineEdit_id.text()
            self.data.loc[self.data.Serial == self.serial,
                          'Gender'] = self.lineEdit_gender.text()
        else:
            self.data.loc[len(self.data.index)] = [
                self.serial, self.lineEdit_name.text(), self.lineEdit_id.text(), self.lineEdit_gender.text()]
        
        print(self.data)
        self.data.to_csv(self.db, index = False)
        self.label_prog.setText("CSV file Updated")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Update/Register"))
        self.label_name_edit.setText(_translate("MainWindow", "Name :"))
        self.label.setText(_translate("MainWindow", "Fill"))
        self.label_id_edit.setText(_translate("MainWindow", "Employee ID :"))
        self.label_gender_edit.setText(_translate("MainWindow", "Gender :"))
        self.label_serial_edit.setText(_translate("MainWindow", "Serial No :"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow(1111, None, "118ME0457", "Male")
#     print(ui.submit_detail)
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
