# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trial_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(10, 10, 871, 71))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(36)
        self.welcome.setFont(font)
        self.welcome.setMidLineWidth(-2)
        self.welcome.setTextFormat(QtCore.Qt.PlainText)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.labelSerial = QtWidgets.QLabel(self.centralwidget)
        self.labelSerial.setGeometry(QtCore.QRect(30, 110, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(24)
        self.labelSerial.setFont(font)
        self.labelSerial.setMidLineWidth(-2)
        self.labelSerial.setTextFormat(QtCore.Qt.PlainText)
        self.labelSerial.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSerial.setObjectName("labelSerial")
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(20, 210, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(24)
        self.labelStatus.setFont(font)
        self.labelStatus.setMidLineWidth(-2)
        self.labelStatus.setTextFormat(QtCore.Qt.PlainText)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.labelSerialValue = QtWidgets.QLabel(self.centralwidget)
        self.labelSerialValue.setGeometry(QtCore.QRect(320, 110, 551, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.labelSerialValue.setFont(font)
        self.labelSerialValue.setMidLineWidth(-2)
        self.labelSerialValue.setText("")
        self.labelSerialValue.setTextFormat(QtCore.Qt.PlainText)
        self.labelSerialValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSerialValue.setObjectName("labelSerialValue")
        self.labelStatusValue = QtWidgets.QLabel(self.centralwidget)
        self.labelStatusValue.setGeometry(QtCore.QRect(320, 210, 551, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.labelStatusValue.setFont(font)
        self.labelStatusValue.setMidLineWidth(-2)
        self.labelStatusValue.setText("")
        self.labelStatusValue.setTextFormat(QtCore.Qt.PlainText)
        self.labelStatusValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatusValue.setObjectName("labelStatusValue")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome.setText(_translate("MainWindow", "Welcome"))
        self.labelSerial.setText(_translate("MainWindow", "Serial Number :"))
        self.labelStatus.setText(_translate("MainWindow", "Status :"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
